<?php

/**
 * Implements hook_menu().
 */
function coax_menu() {
  $items['home'] = array(
    'title' => 'Chicago Event Musicians',
    'page callback' => 'coax_home',
    'access arguments' => array('access content'),
  );
  $items['calendar'] = array(
    'title' => 'Calendar',
    'page callback' => 'coax_calendar',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Page callback: home
 */
function coax_home(){
  $vars = array();
  $home_node = node_view(node_load(669));
  $bands = views_get_view_result('bands', 'pics');
  // dpm($bands);
  $vars['image'] = $home_node['field_image'];
  $vars['body'] = $home_node['field_body'];
  $vars['track'] = $home_node['field_track'];
  $vars['shows'] = views_get_view_result('shows', 'block');
  $vars['bands'] = $bands;
  return theme('jac_home', $vars);
}

/**
 * Page callback: calendar
 */
function coax_calendar(){
  $vars = array();
  $shows_data = views_get_view_result('shows', 'all');
  $shows = array();
  foreach ($shows_data as $show) {
    $shows[] = array(
      'title' => '<div class="cal-band-title">' . $show->node_field_data_field_band_title . '</div>' . $show->node_field_data_field_venue_title . ' - ' . render($show->field_field_time),
      'start' => strip_tags(render($show->field_field_date))
    );
  }
  // dpm($shows);
  $vars['shows'] = json_encode($shows);
  return theme('jac_calendar', $vars);
}

/**
 * Implements hook_theme().
 */
function coax_theme($existing, $type, $theme, $path) {
  return array(
    'jac_home' => array(
      'path' => drupal_get_path('theme', 'jac') .'/templates',
      'template' => 'home',
    ),
    'jac_calendar' => array(
      'path' => drupal_get_path('theme', 'jac') .'/templates',
      'template' => 'calendar',
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function coax_preprocess_page(&$variables) {
  $variables['main_menu'] = drupal_render(menu_tree('main-menu'));
  $band_menu = menu_tree('menu-band-menu');
  foreach ($band_menu as $menu_key => $menu_item) {
    if(is_numeric($menu_key)){
      $node = menu_get_object('node', 1, $menu_item['#href']);
      $band_menu[$menu_key]['#localized_options']['attributes']['data-band-id'] = array($node->nid);
    }
  }
  $variables['band_menu'] = drupal_render($band_menu);
}

/**
 * Implements hook_preprocess().
 */
function coax_preprocess_node(&$variables) {
  $node = $variables['node'];
  if($node->type == 'band'){
    $variables['shows'] = views_get_view_result('shows', 'block', array('nid' => $node->nid));
  }
}

?>